#[derive(PartialEq)]
pub enum Particle{
  Electron,                                                                  
  Hydrogen1,                                                                
  Hydrogen2,                                                                
  Hydrogen3,                                                                
  Helium3,                                                                  
  Helium4,                                                                  
  Lithium6,                                                                 
  Lithium7,                                                                 
  Beryllium9,                                                               
  Boron10,                                                                  
  Boron11,                                                                  
  Carbon12,                                                                 
  Carbon13,                                                                 
  Nitrogen14,                                                               
  Nitrogen15,                                                               
  Oxygen16,                                                                 
  Oxygen17,                                                                 
  Fluorine19,                                                               
  Neon20,                                                                   
  Neon21,                                                                   
  Sodium22,                                                                 
  Sodium23,                                                                 
  Magnesium24,                                                              
  Magnesium25,                                                              
  Aluminium27,                                                              
  Silicon28,                                                                
  Silicon29,                                                                
  Phosphorus31,                                                             
  Sulfur32,                                                                 
  Sulfur33,                                                                 
  Chlorine35,                                                               
  Chlorine36,                                                               
  Chlorine37,                                                               
  Argon39,                                                                  
  Argon40,  
}


impl Particle{

  pub fn g_value(&self) -> f64{

    match self{
      // https://www.physics.nist.gov/cgi-bin/cuu/Value?gem
      Particle::Electron => return -2.00231930436256, 
      Particle::Hydrogen1 => return 5.5869,
      Particle::Hydrogen2 => return 0.857438,
      Particle::Hydrogen3 => return 5.95799,
      Particle::Helium3 => return -4.255,
      Particle::Helium4 => return 0.0,
      Particle::Lithium6 => return 0.822047,
      Particle::Lithium7 => return 2.17095,
      Particle::Beryllium9 => return -0.78495,
      Particle::Boron10 => return 0.600215,
      Particle::Boron11 => return 1.79243,
      Particle::Carbon12 => return 0.0,
      Particle::Carbon13 => return 1.40482,
      Particle::Nitrogen14 => return 0.403761,
      Particle::Nitrogen15 => return -0.566378,
      Particle::Oxygen16 => return 0.0,
      Particle::Oxygen17 => return -0.757516,
      Particle::Fluorine19 => return 5.25774,
      Particle::Neon20 => return 0.0,
      Particle::Neon21 => return -0.441198,
      Particle::Sodium22 => return 0.582,
      Particle::Sodium23 => return 1.47835,
      Particle::Magnesium24 => return 0.0,
      Particle::Magnesium25 => return -0.34218,
      Particle::Aluminium27 => return 1.4566,
      Particle::Silicon28 => return 0.0,
      Particle::Silicon29 => return -1.11058,
      Particle::Phosphorus31 => return 2.2632,
      Particle::Sulfur32 => return 0.0,
      Particle::Sulfur33 => return 0.429214,
      Particle::Chlorine35 => return 0.547916,
      Particle::Chlorine36 => return 0.642735,
      Particle::Chlorine37 => return 0.456082,
      Particle::Argon39 => return -0.4537,
      Particle::Argon40 => return 0.0, 
    }
  }
  //----------------------------------------------------------------------------

  pub fn spin_multiplicity(&self) -> usize {
    match self {
         Particle::Electron => return 2,
         Particle::Hydrogen1 => return 2,
         Particle::Hydrogen2 => return 3,
         Particle::Hydrogen3 => return 2,
         Particle::Helium3 => return 2,
         Particle::Helium4 => return 1,
         Particle::Lithium6 => return 3,
         Particle::Lithium7 => return 4,
         Particle::Beryllium9 => return 4,
         Particle::Boron10 => return 7,
         Particle::Boron11 => return 4,
         Particle::Carbon12 => return 1,
         Particle::Carbon13 => return 2,
         Particle::Nitrogen14 => return 3,
         Particle::Nitrogen15 => return 2,
         Particle::Oxygen16 => return 1,
         Particle::Oxygen17 => return 6,
         Particle::Fluorine19 => return 2,
         Particle::Neon20 => return 1,
         Particle::Neon21 => return 4,
         Particle::Sodium22 => return 7,
         Particle::Sodium23 => return 4,
         Particle::Magnesium24 => return 1,
         Particle::Magnesium25 => return 6,
         Particle::Aluminium27 => return 6,
         Particle::Silicon28 => return 1,
         Particle::Silicon29 => return 2,
         Particle::Phosphorus31 => return 2,
         Particle::Sulfur32 => return 1,
         Particle::Sulfur33 => return 4,
         Particle::Chlorine35 => return 5,
         Particle::Chlorine36 => return 5,
         Particle::Chlorine37 => return 4,
         Particle::Argon39 => return 8,
         Particle::Argon40 => return 1,
    }
  }
}
